sudo: required
language: node_js
addons:
  ssh_known_hosts:
  - hydrock.ru
  - test.hydrock.ru
  - vh20.timeweb.ru
  - git.example.com
  - 92.53.96.68
before_deploy:
- openssl aes-256-cbc -K $encrypted_24f8b4d39db1_key -iv $encrypted_24f8b4d39db1_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 .ssh/deploy_rsa
- ssh-add .shh/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist hydrock@vh20.timeweb.ru:test/public_html
  on:
    branch: master

